spring:
  application:
    name: team
    
  #JDBC (HikariCP) 설정
  # 도커에 환경변수를 등록
  # 로컬 실행시 뒤의 값 실행
  # 도커 실행시 앞의 값 실행
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/xe}
    username: ${SPRING_DATASOURCE_USERNAME:springboot}
    password: ${SPRING_DATASOURCE_PASSWORD:java1234}

  #JPA 설정
  jpa:
    database: oracle
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # 콘솔 로그에 SQL 출력
    properties:
      hibernate:
        format-sql: true # 콘솔 로그 포맷 변경
        highlight_sql: true # SQL 색상 추가

server:
  port: 8888
  
logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace
